---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dokuwiki
  namespace: default
spec:
  chart:
    spec:
      chart: dokuwiki
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: dokuwiki
      version: 13.1.7
  interval: 1m0s
  releaseName: dokuwiki-release

